export const ADD_PRODUCT="ADD_PRODUCT";
export const GET_PRODUCT = "GET_PRODUCT"
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";

export const ADMIN_SIGNIN_SUCCESS = "ADMIN_SIGNIN_SUCCESS"
export const ADMIN_SIGNIN_FAILURE =  "ADMIN_SIGNIN_FAILURE"