export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS"
export const SIGNUP_ERROR = "SIGNUP_ERROR"

export const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS"
export const SIGN_IN_FAILURE =  "SIGN_IN_FAILURE"


export const SHOW_CART_LOADING = "SHOW_CART_LOADING"
export const SHOW_CART_SUCCESS = "SHOW_CART_SUCCESS"
export const SHOW_CART_FAILURE = "SHOW_CART_FAILURE"